[package]
authors = ["Bat' <baptiste@gelez.xyz>"]
name = "plume"
version = "0.1.0"
[dependencies]
base64 = "0.9.1"
bcrypt = "0.2"
chrono = "0.4"
dotenv = "*"
heck = "0.3.0"
hex = "0.3"
openssl = "0.10.6"
reqwest = "0.8"
rocket = "*"
rocket_codegen = "*"
serde = "*"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.diesel]
features = ["postgres", "r2d2", "chrono"]
version = "*"

[dependencies.rocket_contrib]
features = ["tera_templates", "json"]
version = "*"
