[package]
authors = ["Bat' <baptiste@gelez.xyz>"]
name = "plume"
version = "0.1.0"
[dependencies]
bcrypt = "0.2"
dotenv = "*"
rocket = "*"
rocket_codegen = "*"

[dependencies.diesel]
features = ["postgres", "r2d2"]
version = "*"

[dependencies.rocket_contrib]
features = ["tera_templates", "json"]
version = "*"
